function assignNarrator1() { assignNarratorByIndex_(0); }
function assignNarrator2() { assignNarratorByIndex_(1); }
function assignNarrator3() { assignNarratorByIndex_(2); }
function assignNarrator4() { assignNarratorByIndex_(3); }
function assignNarrator5() { assignNarratorByIndex_(4); }
function assignNarrator6() { assignNarratorByIndex_(5); }
function assignNarrator7() { assignNarratorByIndex_(6); }
function assignNarrator8() { assignNarratorByIndex_(7); }
function assignNarrator9() { assignNarratorByIndex_(8); }
function assignNarrator10() { assignNarratorByIndex_(9); }
function assignNarrator11() { assignNarratorByIndex_(10); }
function assignNarrator12() { assignNarratorByIndex_(11); }
function assignNarrator13() { assignNarratorByIndex_(12); }
function assignNarrator14() { assignNarratorByIndex_(13); }
function assignNarrator15() { assignNarratorByIndex_(14); }
function assignNarrator16() { assignNarratorByIndex_(15); }
function assignNarrator17() { assignNarratorByIndex_(16); }
function assignNarrator18() { assignNarratorByIndex_(17); }
function assignNarrator19() { assignNarratorByIndex_(18); }
function assignNarrator20() { assignNarratorByIndex_(19); }
function assignNarrator21() { assignNarratorByIndex_(20); }
function assignNarrator22() { assignNarratorByIndex_(21); }
function assignNarrator23() { assignNarratorByIndex_(22); }
function assignNarrator24() { assignNarratorByIndex_(23); }
function assignNarrator25() { assignNarratorByIndex_(24); }
function assignNarrator26() { assignNarratorByIndex_(25); }
function assignNarrator27() { assignNarratorByIndex_(26); }
function assignNarrator28() { assignNarratorByIndex_(27); }
function assignNarrator29() { assignNarratorByIndex_(28); }
function assignNarrator30() { assignNarratorByIndex_(29); }
function assignNarrator31() { assignNarratorByIndex_(30); }
function assignNarrator32() { assignNarratorByIndex_(31); }
function assignNarrator33() { assignNarratorByIndex_(32); }
function assignNarrator34() { assignNarratorByIndex_(33); }
function assignNarrator35() { assignNarratorByIndex_(34); }
function assignNarrator36() { assignNarratorByIndex_(35); }
function assignNarrator37() { assignNarratorByIndex_(36); }
function assignNarrator38() { assignNarratorByIndex_(37); }
function assignNarrator39() { assignNarratorByIndex_(38); }
function assignNarrator40() { assignNarratorByIndex_(39); }
function assignNarrator41() { assignNarratorByIndex_(40); }
function assignNarrator42() { assignNarratorByIndex_(41); }
function assignNarrator43() { assignNarratorByIndex_(42); }
function assignNarrator44() { assignNarratorByIndex_(43); }
function assignNarrator45() { assignNarratorByIndex_(44); }
function assignNarrator46() { assignNarratorByIndex_(45); }
function assignNarrator47() { assignNarratorByIndex_(46); }
function assignNarrator48() { assignNarratorByIndex_(47); }
function assignNarrator49() { assignNarratorByIndex_(48); }
function assignNarrator50() { assignNarratorByIndex_(49); }